### ISSUE TITLE
Aurelia-Http dependency issue

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#101]
**I'm submitting a bug report**
```
ERROR in ./node_modules/aurelia-slickgrid/dist/native-modules/filters/selectFilter.js
Module not found: Error: Can't resolve 'aurelia-http-client' in '.\node_modules\aurelia-slickgrid\dist\native-modules\filters'
```

* **Library Version:**
2.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Bundler used (WebPack/RequireJS/SystemJS)**
Webpack with aurelia cli

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
The library requires the use of aurelia-http-client

**Expected/desired behavior:**

* **What is the expected behavior?**
The library should not require this library and throw this error

* **What is the motivation / use case for changing the behavior?**
This may not give a good user experience because the grid should work "out of the box". Many user will probably use aurelia's library, but we should not force them to do so, especially since the aurelia CLI does not install the aurelia-http-client with `au new`. 

I found this when starting a new application trying to create a simple 3 column grid where my API call was mocked. This library is found in the select filter and the main custom element used with `instance of` and to define a type for the parameter.

EDIT: Actually I forgot the fetch-client and http-client are two different libraries. Some users may only use the fetch-client.

**Comment by ghiscoding** [comment]
I thought about that but how do you propose to go around it? How can I check the `instanceof` if we can't put these lib as `dependencies`? Unless there's other ways to detect when it's 1 or the other in the Filter Service. Maybe just checking the method name called would be enough? I think they are different methods, so that might work

**Comment by jmzagorski** [comment]
Yup. One is `content` and the other is `json`. Check for `json` first, then fallback to `content`

**Comment by ghiscoding** [comment]
I also support Promise, so I'll have to check that one too (not currently looking at the code).
