### ISSUE TITLE
Windows 10 Install Errors with a fix for client-cli

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#139]
**I'm submitting a bug report**
* **Library Version:**
\aurelia-slickgrid\client-cli
node v10.15.0
npm 6.4.1

* **Operating System:**
Windows 10 Home

* **Bundler used (WebPack/RequireJS/SystemJS**
client-cli

* **Browser:**
 Chrome 
* **Language:**
 ESNext

**Current behavior:**
Command failed: C:\Program Files\Git\cmd\git.EXE checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git.

**Expected/desired behavior:**
get npm install to work

* **What is the expected behavior?**
found reference  https://github.com/olefredrik/FoundationPress/issues/1312
and did the following
had this issue as well, Changing `package.json` from `"gulp": "github:gulpjs/gulp#4.0"` to `"gulp": "4.0"` **AND** deleting my `package-lock.json` solved the issue.

The issue is the branch was deleted, for backwards compatibility can we keep the git branch active and maybe add a warning on `postinstall`?

* **What is the motivation / use case for changing the behavior?**
To have demo working locally
P.S. I tried to do the same for aurelia-slickgrid\doc\github-demo but got too many errors to report and happy to see cli working and thanks for your incredible contributions!

**Comment by ghiscoding** [comment]
oh thanks for providing that. I'm a bit surprised about the demo throwing errors, I got none on my side but it was installed some time ago. There's also a 3rd demo that you could try which is in a separate repo, it's the [Bootstrap 4 demo](https://github.com/ghiscoding/angular-slickgrid-bs4-demo). I'll have to test all demos from scratch when I get a chance and see what comes up.

**Comment by ghiscoding** [comment]
I made the change as you mentioned for the `client-cli`, for me it doesn't make any difference before or after, but if that helps on your side then it's good. 

As for the `github-demo` errors, are these the errors you meant?

```shell
[at-loader] Checking finished with 49 errors
[at-loader] ./dist/common.f6befe4528c4f56bface.bundle.js:35:21561
    TS1003: Identifier expected.

[at-loader] ./dist/common.f6befe4528c4f56bface.bundle.js:35:21567
    TS8010: 'types' can only be used in a .ts file.
```
These errors came up some time ago but I never took the time to investigate more since at the end the project still runs fine. It seems to more of a lint issue and it still uses WebPack 3, the best that I should do is upgrade is to latest Aurelia CLI with WebPack 4, but time is limited. Anyhow like I said, the project still runs fine and there's no error in the console, which is the most important part.

**Comment by johntom** [comment]
So I installed the [Bootstrap 4 demo](https://github.com/ghiscoding/angular-slickgrid-bs4-demo) after installng node 11.10.0.
```
PS D:\Aurelia\2019\aurelia-slickgrid-bs4-demo> au build
(node:39372) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: 3b9eebda065a42603a3f
Version: webpack 4.29.4
Time: 11725ms
Built at: 02/18/2019 9:39:40 AM
                                  Asset       Size  Chunks                    Chunk Names
   674f50d287a8c48dc19ba404d20fe713.eot    162 KiB          [emitted]
   912ec66d7572ff821749319396470bde.svg    434 KiB          [emitted]  [big]
 af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB          [emitted]
     app.3b9eebda065a42603a3f.bundle.js     13 MiB     app  [emitted]  [big]  app
assets/data/collection_100_numbers.json   6.46 KiB          [emitted]
assets/data/collection_500_numbers.json   23.4 KiB          [emitted]
             assets/data/countries.json   9.98 KiB          [emitted]
         assets/data/country_names.json   4.29 KiB          [emitted]
         assets/data/customers_100.json   6.83 KiB          [emitted]
     assets/data/customers_100_ASC.json   6.83 KiB          [emitted]
    assets/data/customers_100_DESC.json   6.83 KiB          [emitted]
            assets/data/example-data.js  421 bytes          [emitted]
     assets/locales/en/translation.json   1.93 KiB          [emitted]
     assets/locales/fr/translation.json   2.18 KiB          [emitted]
   b06871f281fee6b241d60582ae9369b9.ttf    162 KiB          [emitted]
  fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB          [emitted]
                             index.html  824 bytes          [emitted]
  vendor.3b9eebda065a42603a3f.bundle.js   1.23 MiB  vendor  [emitted]  [big]  vendor
Entrypoint app [big] = app.3b9eebda065a42603a3f.bundle.js
Entrypoint vendor [big] = vendor.3b9eebda065a42603a3f.bundle.js
[0] multi aurelia-webpack-plugin/runtime/empty-entry aurelia-webpack-plugin/runtime/pal-loader-entry aurelia-bootstrapper 52 bytes {app} [built]
[1] multi bluebird jquery 40 bytes {vendor} [built]
[./node_modules/aurelia-bootstrapper/dist/native-modules/aurelia-bootstrapper.js] 5.51 KiB {app} [built]
[./node_modules/aurelia-loader-webpack/dist/native-modules/aurelia-loader-webpack.js] 15.2 KiB {app} [built]
[./node_modules/aurelia-pal/dist/native-modules/aurelia-pal.js] 2.18 KiB {app} [built]
[./node_modules/aurelia-polyfills/dist/native-modules/aurelia-polyfills.js] 24.2 KiB {app} [built]
[./node_modules/aurelia-webpack-plugin/runtime/empty-entry.js] 585 bytes {app} [built]
[./node_modules/aurelia-webpack-plugin/runtime/pal-loader-entry.js] 1.56 KiB {app} [built]
[./node_modules/bluebird/js/browser/bluebird.js] 176 KiB {app} {vendor} [built]
[./node_modules/bluebird/js/browser/bluebird.js-exposed] 65 bytes {app} {vendor} [built]
[./node_modules/expose-loader/index.js?jQuery!./node_modules/jquery/dist/jquery.js-exposed] ./node_modules/expose-loader?jQuery!./node_modules/jquery/dist/jquery.js-exposed 62 bytes {app} {vendor} [built]
[./node_modules/jquery/dist/jquery.js-exposed] 149 bytes {app} {vendor} [built]
[./node_modules/process/browser.js] 5.29 KiB {app} {vendor} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {app} {vendor} [built]
[aurelia-framework] ./node_modules/aurelia-framework/dist/native-modules/aurelia-framework.js 16.5 KiB {app} [built]
    + 550 hidden modules
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.36 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.ejs] 1.13 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
PS D:\Aurelia\2019\aurelia-slickgrid-bs4-demo>
```

**Comment by ghiscoding** [comment]
I don't see any errors in what you posted, is there any errors? Also if you use VSCode as your editor, you should see 2 tasks, 1 to Build and 1 to Run the demo. It looks like you built the demo, you probably want to run it instead

**Comment by johntom** [comment]
Sorry, I left out the followin when I enter http://localhost:8081/ in browser I get the following:
```
i ｢wdm｣: wait until bundle finished: /app.3b9eebda065a42603a3f.bundle.js
i ｢wdm｣: wait until bundle finished: /vendor.3b9eebda065a42603a3f.bundle.js
× ｢wdm｣: ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.
    at Compiler.run (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack\lib\Compiler.js:211:37)
    at rebuild (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack-dev-middleware\lib\context.js:81:24)
    at done (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack-dev-middleware\lib\context.js:59:7)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:18:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\tapable\lib\Hook.js:154:20)
    at emitRecords.err (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack\lib\Compiler.js:267:22)
    at Compiler.emitRecords (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack\lib\Compiler.js:449:39)
    at emitAssets.err (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack\lib\Compiler.js:261:10)
    at hooks.afterEmit.callAsync.err (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack\lib\Compiler.js:435:14)
    at _err0 (eval at create (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:20:1)
    at callback (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\copy-webpack-plugin\dist\index.js:126:17)
    at afterEmit (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\copy-webpack-plugin\dist\index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\tapable\lib\Hook.js:154:20)
    at asyncLib.forEachLimit.err (D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\webpack\lib\Compiler.js:432:27)
    at D:\Aurelia\2019\aurelia-slickgrid-bs4-demo\node_modules\neo-async\async.js:2813:7


```

**Comment by ghiscoding** [comment]
Ah the joy of programming... it's works on my computer... I don't have a clue what is the error that you have, there's not much info apart from saying that Webpack ran twice?? Your output also seems to be a Build output, not a Run output. What is the command or the task that you tried running?

I would suggest that you try creating a new project via the CLI and that should work, else I'll have to investigate more. Also like I said earlier, I'll have to redo the GitHub Demo with latest version of CLI and WebPack 4, just not sure when I'll have time to do that though.

**Comment by ghiscoding** [comment]
@johntom 
I see the problem, you are running `au build`, however there are some problems with the CLI (at least the version I have installed) and so I always used the previous, and working, command which is `npm start` (or `yarn start`) and `npm start build` (or `yarn start build`). Basically there was a problem in the past with the CLI and WebPack, I'm not sure if they ever fixed the issue.

That should resolve your issue with that demo

**Comment by johntom** [comment]
I will test asap, was in the field yesterday and could not follow up. Thanks for your prompt attention.

**Comment by johntom** [comment]
npm start fixed the issue with this start and I use that command for many projects but thought this required au run! This is Awesome and  in a previous client-cli build I changed over to aurelia-client-fetch for getting data from a nodejs server with a mongodb payload. Will post a little how to in the issue section very soon and hopefully write a blog which I haven't done on a long time. 

Also, while I prefer the cli/javascript over webpack/typescript this demo project support async/await which I use all the time. At the end of the day I look forward to aurelia-next and aurelia script as I think whis will be a big step forward.

**Comment by ghiscoding** [comment]
@johntom 
Thanks for the feedback, I will add a README on that Bootstrap 4 demo, it should you and others if they wish to have a working demo. I did not try the latest CLI, so perhaps they fixed the `au run` with WebPack, when I build the BS4 demo it wasn't working so I still use the old command. 

If you try the latest CLI with WebPack, could you try `au run` and let me know if it works. I should also rename the `client-cli` folder to maybe `client-requirejs` since it's RequireJS, at the time I created that folder the CLI had limited functionality.

I also use async/await, I love that new style and I'm all in with TypeScript, it removes so much potential bugs right from the start. 

I'll be sure to read your blog, please send over the link when that happens 😃 
Again thanks for all feedbacks
