### ISSUE TITLE
PageSizes wrong parameters

### ISSUE THREAD

**Issue by audrys** [ghiscoding/aurelia-slickgrid#150]
Hi,
I would like to set own page sizes for the grid.
In gridOptions I added parameters:
```ts
pagination: {
        pageSizes: [50, 100, 500],
        pageSize: 100,
        totalItems: 0
      }
```
In result I have got my sizes on the top of default (25,30,40,50,75,100).
Thanks for the help

**Comment by ghiscoding** [comment]
Pagination is only used with the `backendServiceApi`, are you using it? If so that is the correct way of changing the options.

**Comment by audrys** [comment]
Hi,
Thanks for answer.
Yes, I am using bacckendServerApi:
...
backendServiceApi: {
        service: new GridOdataService(),
        preProcess: () => this.dataLoaded.emit(false),
        process: (query) => this.getCustomerApiCall(query),
        postProcess: (response) => {
          this.dataLoaded.emit(true);
          this.getCustomerCallback(response);
        }
      }
BR

**Comment by ghiscoding** [comment]
I could check later with OData, it should work. 

Just wondering, are you using Angular and Aurelia at the same time? 
I see you creating issues in both of my libs, are you really using both frameworks?

**Comment by audrys** [comment]
Hi, 

No I am using just Angular. 

Sry. did not recognize about Aurelia

---
Best Regards
Audrius Valentinas 

On 2019-04-01 17:18, Ghislain B. wrote:

> I could check later with OData, it should work. 
> 
> Just wondering, are you using Angular and Aurelia at the same time?
> I see you creating issues in both of my libs, are you really using both frameworks? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/ghiscoding/aurelia-slickgrid/issues/150#issuecomment-478622484
[2]

**Comment by ghiscoding** [comment]
I have pushed a [commit](https://github.com/ghiscoding/Angular-Slickgrid/commit/8ea07447d4e6635274d7e25955868b14ef568617) in Angular-Slickgrid repo to address the original issue. I will wait a few more days to release a new version though.

**Comment by ghiscoding** [comment]
@audrys 
The fix was pushed and released in the Angular-Slickgrid repo last week, you can update your version to [2.4.6](https://github.com/ghiscoding/Angular-Slickgrid/releases/tag/v2.4.6).

Also please make sure to open issue in respective repo, I maintain both Angular & Aurelia repos but the code base is slightly different in each (about 10-15% is different). 

Thanks for the feedback
