### ISSUE TITLE
Need a single search box for filtering instead of one on each coloumn

### ISSUE THREAD

**Issue by atreya-yelishetti** [ghiscoding/aurelia-slickgrid#152]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**

**Please tell us about your environment:**
* **Operating System:**
Windows [|10]

* **Bundler used (WebPack/RequireJS/SystemJS**
 WebPack
* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView

* **Language:**
 TypeScript 

**Current behavior:**
There are filters on top of each column

**Expected/desired behavior:**
To have a single input field above the grid which searches in all the columns. Can I know how to do it? Just some brief pointers would be helpful and highly appreciated. 

In the image attached you can see what my expectations are, when I select all it should search in all the columns or if I select any specific column, it should search in that particular column. Currently we are using au-table to achieve this, and we are moving away from au-table to aurelia-slickgrid, as slickgrid is amazing with plenty of features. 
![Screenshot (66)](https://user-images.githubusercontent.com/49288643/55584802-c0e3c780-56ea-11e9-8ecc-97313d1e56a0.png)

**Comment by ghiscoding** [comment]
The closest thing that is available is a Compound Input Filter (as shown below), were the dropdown is a list of possible Operator to use by the search filter. However the list of Operators is not currently editable, for now it only goes by the FieldType and when it's a string the Operators list will be `[equal, startsWith, endsWith]` while anything else will have following `[=, <, <=, >, >=, <>]`. 

The other difference that I see with your print screen and the built-in Compound Input Filter is the width of the dropdown, I basically used Bootstrap [Input Group](https://getbootstrap.com/docs/3.4/components/#input-groups), but looking at Bootstrap again and perhaps I should have used [Input Groups Buttons](https://getbootstrap.com/docs/3.4/components/#input-groups-buttons-dropdowns) instead which looks more like your print screen.

If you want to contribute and help with a PR, I'd be more than happy to get this in. I always thought the dropdown width is a bit small to look at. For the Compound Input Filter to support what you want, I think it needs the following 2 things to happen
1. support custom list of Operators
2. convert Bootstrap [Input Group](https://getbootstrap.com/docs/3.4/components/#input-groups) to  [Input Groups Buttons](https://getbootstrap.com/docs/3.4/components/#input-groups-buttons-dropdowns).
   - also need to support both Bootstrap 3 and 4 version

![image](https://user-images.githubusercontent.com/643976/55593222-13cc7780-5709-11e9-953a-768c06f757be.png)

**Comment by atreya-yelishetti** [comment]
From the screen shot image I could see that is a filter on top of one coloumn, I want a common search box above the grid where the dropdown contains list of coloumn names and All. If user selects All it will search in all the coloumns of the grid, if user selects a particular coloumn name, it should search only in that particular row.

**Comment by atreya-yelishetti** [comment]
I don't have much knowledge on UI development. I'm a beginner and making use of your examples to make my requirements meet. If you can give me an insight on what needs to be done, I'm happy to create a pull request and add this feature. Thank you.

**Comment by ghiscoding** [comment]
Back to your original question, I've looked in making a demo and good news, you can already do it with current version. For a reference you can see the PR #157 which includes an animated gif displaying the result. Also note I also added the Operator (2nd dropdown) but if you wish to use an Equal all the time, you can fix it in your code, the code is very flexible. 

Have fun and don't forget to up vote ⭐️ the lib

**Comment by atreya-yelishetti** [comment]
Awesome. This will help me. Thanks a lot.

**Comment by ghiscoding** [comment]
You can leave the issue open until I merge the PR later in the week.
