### ISSUE TITLE
Multiple grids in one view - gridStateService issue

### ISSUE THREAD

**Issue by AlexN2805** [ghiscoding/aurelia-slickgrid#190]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Aurelia-Slickgrid | 2.10.1
| TypeScript        | 2.9.2
| Operating System  | Windows 10

### Context
I currently have 2 slickgrids in the same view. I want to save both their states to the database. The problem however is that the gridStateService still seems to be a singular object. So only the state of the 2nd grid is saved correctly.

### Expected Behavior
I expected that both grids have their own gridStateService, so both states can be saved.

### Current Behavior
Only the 2nd grid saves it's state correctly. I've been testing some of the variables and the result was:
this.gridRequest.exportService === this.gridAvailability.exportService -> false
this.gridRequest.extensionService === this.gridAvailability.extensionService -> false
this.gridRequest.filterService === this.gridAvailability.filterService -> false
this.gridRequest.gridEventService === this.gridAvailability.gridEventService -> false
this.gridRequest.groupingService === this.gridAvailability.groupingService -> false
this.gridRequest.gridStateService === this.gridAvailability.gridStateService -> true
this.gridRequest.sortService === this.gridAvailability.sortService -> false
this.gridRequest.gridService === this.gridAvailability.gridService -> false

It seems that the gridStateService is shared amongst the 2 grid, causing this problem.

**Comment by ghiscoding** [comment]
Good catch, it seems we forgot to add the `@singleton(true)` on top of the Service like all other services, for example this [line](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/services/grid.service.ts#L17) is for the GridService. I'll have to review all Services to make sure they are singleton

**Comment by ghiscoding** [comment]
@AlexN2805 
This is now released under version [2.11.3](https://github.com/ghiscoding/aurelia-slickgrid/releases/tag/v2.11.3)

Up vote if you like the lib
Cheers ⭐️
