### ISSUE TITLE
Server side pagination with Fetch

### ISSUE THREAD

**Issue by si2030** [ghiscoding/aurelia-slickgrid#196]
You wrote in the Aurelia Discourse...

> Pagination is not currently available for local dataset (like a JSON dataset coming from Http). I might add it in the future, but it is really low, low, low priority. The reason, is that with local dataset, all the data exist locally in your browser cache anyway, so there’s not much point in adding pagination for it since you won’t save anything in download.

> On the other end, the backend service (when using the grid optionbackendServiceApi with the GridOdataService or the GraphqlService), do use pagination simply because they are built with pagination in mind. That is to say, unless you have a backend server with OData (mostly with .Net), then only at that time you would add the backendServiceApi to your grid option. If you’re planning on using something else than OData or GraphQL, you could in theory create your own backendServiceApi (1 guy did it with Angular-Slickgrid with an Oracle DB which uses different querying strings). The process method is a callback which uses the GridOdataService to build the query string, so the query comes from the Service and is what you typically connect to your Http call.

> The statistics are simply metadata showing certain statistics of the grid like the size of the dataset, how long it took to get the data, and things like that, maybe the name isn’t too good, I was out of idea at the time on how to name it (if you have a better name, send it over and I might go for a rename).
> If you think some of the Wikis can be improved, then please open an issue on the project and I’ll update them with your comments.

I need (I think) server side pagination where if the client clicks on page 2 there is a call back to the server for page 2 of data and of course if there is a filter a call back for that too.

Currently I have Aurelia-Table working but as a friend indicated to me some time ago (professional programmer so definitely the other end of the spectrum) that client side pagination is dangerous with an ever larger dataset. In this vein I want to do server side pagination with Fetch however I dont know how to implement this into example 5 I believe... or if this is even possible. Currently its mock data using http-client. 

So what I am asking is.. is this a situation where it downloads the full dataset or a server side pagination call etc and if not can I make it so it does server calls?

If so can I make Fetch calls instead.

Simon
PS thanks for creating all this in the first place..

**Comment by ghiscoding** [comment]
Hello, I did mention that the `backendServiceApi` are meant to be used with OData or GraphQL, that is your backend server must be using 1 of these 2. If your backend server already implements OData, then there's almost nothing to do, just use it as Example 5 and replace the Http call with your own API and that's it. At my work, we use the GraphQL implementation, which is why it exists in this lib (actually we use Angular-Slickgrid, which I support as well).

Using regular Http with a JSON dataset is the easier, and your friend is right in saying that if your dataset grows, you must be thinking about pagination but for that you need your backend to support it, OData, GraphQL are just 2 of the ways to do that. SlickGrid will work just fine with 10k rows locally

**Comment by ghiscoding** [comment]
@si2030 
Have you figured out how to use the grid with backend? 
Can we close this issue?

**Comment by si2030** [comment]
Hi @Gishcoding.. sorry for being slow.. life.. you know.. Anyway I decided to implement Odata and it worked on an Asp.net CORE 2.2... the problem though is that I have my entire project ported to asp.net CORE 3.0 and the buggers havent actually upgraded Odata to work on 3.0 yet.. so I am contemplating mocking the response manually that would normally come from Odata on the server which I have yet to do.  

I am intending to use fetch at the point hopefully but with Odata once they implement it for CORE 3.0.. whenever that happens.

Is it possible to use fetch for the purposes of connecting to odata at the server end.. I'm thinking it should be.. however  I note you have been using aurelia-http-client.. I dont think I need to change to this do I?

...and whilst its a lot of work I should be able to mock the return data signature that Odata would send back?

**Comment by ghiscoding** [comment]
@si2030 
I'm not sure to understand the entire context of your comment, but you seem to have misunderstood what the `GridOdataService` actually does. It's only purpose is to build an OData query string, and nothing else, it knows nothing about your backend and it doesn't care either. Next, the only thing you have left to do (as a user of the grid) is to connect the `process` callback method of the `backendServiceApi` with whatever Http Client you want to use (Http,Fetch or even a simple Promise), the only requirement is that it must return a promise with the data. 

Basically something like the following should be enough
```ts
constructor(private http: FetchClient) {
  this.defineGrid();
}

defineGrid() {
  this.columnDefinitions = [ /*...*/ ];

  this.gridOptions = {
    backendServiceApi: {
      service: new GridOdataService(),

      // with Fetch
      process: (query) => this.http.fetch('api/users').then(response => response.json()),
        
      // or with regular Http
      // process: (query) => this.http.createRequest('api/users').asGet().send().then(response => response.content),
    }
  };
}
```
For the explanation of it all in multiple steps
1. The `GridOdataService` builds the query string and sends it to the `process` method callback
2. The `process` callback takes this new query string and sends it to the API (through Http/Fetch or Promise)
3. The `process` waits for the API to response with the Promise (await)
4. The promise resolves and the grids is refreshed with the data provided
5. ... and we are done! ...until something else happens (filter/sort/page), when that happens we restart to step 1

**Comment by si2030** [comment]
Really appreciate your answer.. this demystify's it alot. I shall use this as the basis for creating the basic grid.

Re the comment on Odata and Asp.net Core.. its actually not available until they release it later this year I suspect.

With what you have given me I can work with that.. very much appreciated.

Closing this.. if I have any other issues I cannot resolve I will start a new issue. Response here was fantastic.

Simon

**Comment by ghiscoding** [comment]
I think OData is already available under .Net Core 2.0, read this [article](https://devblogs.microsoft.com/odata/asp-net-core-odata-now-available/).

**Comment by si2030** [comment]
Thanks for having a look.. :) however sadly OData has yet to be offered for .Net Core 3.0.. I learn the hard by blindly implementing it and then finding it crashing my project.. I then went searching and found [this](https://github.com/OData/WebApi/issues/1748).. :(
