### ISSUE TITLE
Filters are out of sync since the Filter Factory implementation

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/aurelia-slickgrid#20]
**I'm submitting a bug report**
* **Browser:**
all
* **Language:**
TypeScript

**Current behavior:**
The current `Filter` class has multiple properties like `columnDef`, `callback`, `searchTerm`, ... all of which are associated to the current column filter element. However the Filter Factory has a `this.filters.find` function which has a side effect of overwriting (or re-using) previous column filter. For example, let say column 1 and 4 are input filter, column 2 and 3 are select filter, then the current behavior of that column 1 will create a filter in the factory because it didn't find any but then when it comes back to the factory for column 4, it finds a filter and returns it but a new `columnDef` associated and column1 filter becomes out of sync (now it's columnDef is associated to column 4, so when I start typing in column 1 it tries to filter data against column 4.

**Expected/desired behavior:**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
I think this is a bad design from my side and `Filter` should be separated into 2 different classes, making something like `ColumnFilter` and `ElementFilter` classes were `ElementFilter` should only have the behavior of a DOM element (that one would stay with the Filter Factory) but the ColumnFilter class would have each `columnDef` and other related properties. This new issue was not there before the Filter Factory was introduced. I don't see this problem in Angular since I haven't put the Factory pattern in that repo yet and the previous code was creating a new instance on every filter element which is a difference compare to the Filter Factory which does a `find()`.

For example, the first print screen below shows the `columnDef` before creating the filter and we can see it's associated to "percentComplete" but then it goes in the createFilter Factory, it finds a filterType and returns it but then that filter already has a `columnDef` associated to it, which is "Title". So now, when I start typing a filter in "percentComplete", it's actually trying to filter on "title"

Before creating the filter, it's `columnDef` is "percentComplete"
![filter1](https://user-images.githubusercontent.com/643976/36826786-c37e6d08-1cdd-11e8-81e7-28b31fa4d1f6.png)

After creating the filter, it's now associated to `columnDef` of "title"
![filter2](https://user-images.githubusercontent.com/643976/36826797-d0922980-1cdd-11e8-9374-da1ed77ba47b.png)

**Comment by jmzagorski** [comment]
Oh yes you are right, the factory class should create a new instance every time it is called. I did not test this thoroughly enough since I only tested it on one column, sorry.

I will put in a fix today so the factory creates a new class every time, that should fix the problem without having to rewrite the interface for now

**Comment by ghiscoding** [comment]
I just realized that the main issue is because the Filter Factory now create singletons and I pass the `filterArguments` [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/services/filter.service.ts#L333) and these include the `columnDef` and other properties of each column filter.

**Comment by jmzagorski** [comment]
yup, totally my fault in missing the way `Filters` were used. A potential fix is cloning the classes (see below). Not the prettiest and surely not the Aurelia way since I am not sure the performance implications, but it should deep clone a class excluding static props/methods I think. And it is the quickest thing I can think of.

```javascript
 import { inject, All } from 'aurelia-framework';
import { Filter, FilterType, FormElementType } from '../models/index';

/** The name of the plugins the factory will initialize via Aurelia's All.Of */
export const PLUGIN_NAME = 'GRID_FILTERS';

/**
 * Factory class to Instantiates a Filter interface implementation
 */
@inject(All.of(PLUGIN_NAME))
export class FilterFactory {

  /**
   * Creates an instance of the FilterFactory class
   * @param {Filter[]} filters the array of supported Filter interfaces
   * @param {FilterType} [defaultFilterType=FilterType.input] an optional default filter type to use
   * when no filter type is found. Supply a different default value using Aurelia's Factory.Of
   * resolver
   */
  constructor(
    private filters: Filter[],
    private defaultFilterType: FilterType | FormElementType = FilterType.input
  ) { }

  /**
   * Creates a new Filter from the provided filterType
   * @param {FilterType | FormElementType | string} filterType the type of filter to create
   * as an enum or custom string
   * @return {Filter} the new Filter
   */
  public createFilter(filterType: FilterType | FormElementType | string): Filter {
    const filter: Filter | undefined = this.filters.find((f: Filter) =>
      f.filterType === filterType);

    // default to the input filter type when none is found
    if (!filter) {
      const inputIndex: number = this.filters.findIndex((f: Filter) =>
        f.filterType === this.defaultFilterType);

      if (inputIndex === -1) {
        throw new Error(`Default filter of type ${FilterType[this.defaultFilterType] || this.defaultFilterType} was not found`);
      }

      return this._clone(this.filters[inputIndex]);
    }

    return this._clone(filter);
  }

  private _clone(instance: Filter): Filter {
    return Object.assign(Object.create(Object.getPrototypeOf(instance)), instance);
  }
}
```
```

**Comment by ghiscoding** [comment]
Does the Factory Pattern always return singleton or can it be changed to return new instances every time?

**Comment by jmzagorski** [comment]
a class using the factory pattern, such as the `FilterFactory` is suppose to create a new instance every time the method is called, so I totally botched this commit. I should have created a unit test because that would have showed me immediately that I implemented this wrong!

I am going to find a better implementation if you just want to use my quick solution, and I am going to unit test it so this problem doesn't happen again.

**Comment by ghiscoding** [comment]
Don't be so hard on yourself, the fact that I don't have any unit testing in this project doesn't help. I should have tried it a bit more myself before merging. It's not the end of the world anyway, so take your time in finding what you think will be a better solution and if you can't find the best way of doing it until I push a new version Saturday or Monday, then I'll take your quickest and dirty code. Thanks

**Comment by jmzagorski** [comment]
So i have a fix for this, but had a question:

Currently in the `FilterFactory` there is a argument in the constructor for a `defaultFilterType` that we can override when injecting the `FilterFactory`. What if we added a `defaultFilterType` to the `SlickgridConfig` that the user can override with their own configuration during the startup of the app when we pass the config object to them in `maint.ts` here:

```
  if (typeof callback === 'function') {
    callback(config);
  }
```

**Comment by ghiscoding** [comment]
You mean still setting the `defaultFilterType` to `FilterType.input` but giving a possibility to change that default? I'm ok with that as long as it doesn't require the user to do any code change in the next release.

**Comment by jmzagorski** [comment]
When i try to run the build I get an error from the master branch at the `multipleSelectOption.interface.ts` at [Line 129](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/models/multipleSelectOption.interface.ts#L129) and [Line 130](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/models/multipleSelectOption.interface.ts#L130). Do you get these as well?

aurelia-slickgrid/src/aurelia-slickgrid/models/multipleSelectOption.interface.ts(129,20): error TS7006: Parameter 'any' implicitly has an 'any' type.

aurelia-slickgrid/src/aurelia-slickgrid/models/multipleSelectOption.interface.ts(130,19): error TS7006: Parameter 'any' implicitly has an 'any' type.

**Comment by ghiscoding** [comment]
Ah those are part of some changes that I've done during the week that are merged in master branch though I didn't try to build since last week. I usually fix these build issues when I'm at the build stage. 

Anyhow, I made a big mistake on those line when I created (all by hand) this interface. You cannot do that `(any)` in TypeScript, it's not valid. Can you try to change it for this instead:
```javascript
  /** Returns HTML label attribute of a DOM element */
  labelTemplate?: (elm: any) => any;

  /** Returns HTML text template of a DOM element */
  textTemplate?: (elm: any) => any;
```
Sorry about that

**Comment by jmzagorski** [comment]
no worries. I didn't know if you wanted me to change that or not. I will include that in my pull request.

**Comment by ghiscoding** [comment]
yes please go ahead.

you're actually lucky that there isn't more build issues, I usually get a ton since the TSConfig is a bit too tight for my taste. I might loosen it up in the future.

**Comment by ghiscoding** [comment]
Closing since the fix was merged. Thanks
