### ISSUE TITLE
Odata requesting the concatenation of two fields to display as one

### ISSUE THREAD

**Issue by si2030** [ghiscoding/aurelia-slickgrid#202]
Hi there, quick question. I am setting up a grid for Odata however my database has separate fields for "first-name" and "last-name". 

I'd like to combine these into one field called "Name" eg "**Brown**, John" and "**Doe**, Jane" how do I structure the Slickgrid to do this.

Further, I'd also like to convert the surname to bold style as above, when combining the two table columns.

I am assuming that this is done in column definitions but I've looked and haven't been able to find anything on this yet.. sure its there though.

**Comment by ghiscoding** [comment]
with a Custom Formatter

**Comment by si2030** [comment]
Thanks mate.. will have a look.
