### ISSUE TITLE
Creating a Aurelia Slickgrid inside a detail view

### ISSUE THREAD

**Issue by si2030** [ghiscoding/aurelia-slickgrid#223]
I know your busy... and of course the last thing is to bug you with a trivial question (which this could be) but I am finding this quite difficult to do and it may be because I want this to appear in an Aurelia custom element being a detailed view for one of the Slickgrid rows.

I've created a detailed view that you open via the "+" icon at the start of each record and it works really well.. so thats all good.. By the way your package makes me look a lot better than I really am.. thank you for that.  

I wanted to also display a simple list of jobs for the client inside in the detailed view and so set about creating an Aurelia Slickgrid in the detailed view on the right side however it wont show at all and not even the headings.. 

I have confirmed I am getting the data via the Aurelia preview pane but it doesnt even want to throw up the headings... Here is the detail-view viewmodel with the Slickgrid implementation... 

I have tried to define the grid in the bind because being a custom element I don't have access to attached.. 

```
	import { bindable, PLATFORM, autoinject } from "aurelia-framework";
	import {
		AureliaGridInstance,
		Column,
		FieldType,
		Formatters,
		Filters,
		GridOption
	} from 'aurelia-slickgrid';

	@autoinject
	export class ClientIndexDetailViewCustomElement {
		@bindable detailViewRowCount = 7;
		aureliaGrid: AureliaGridInstance;
		gridOptions: GridOption;
		columnDefinitions: Column[];
		jobsDataset: any[];

		@bindable() model: {
			id: number;
			clientNo: number;
			company: boolean;
			isWarrantyCompany: boolean;
			CompanyName: string;
			ClientFirstName: string
			ClientLastName: string
			MobilePhone: string
			DateCreated: string
			DeActivated: string
			NumberOfJobs: string
			Active: boolean
			Activity: boolean
			Address: any
			jobs: any[]
		};

		bind(bindingContext, overrideContext) {
			this.defineGrid();

			if (bindingContext.model) {
				this.model = bindingContext.model;
				console.log("client-detail-MODEL 1: ", this.model);
			} else if (overrideContext && overrideContext.bindingContext && overrideContext.bindingContext.model) {
				this.model = overrideContext.bindingContext.model;
				console.log("client-detail-MODEL 2: ", this.model);
			} else if (overrideContext && overrideContext.parentOverrideContext && overrideContext.parentOverrideContext.bindingContext && overrideContext.parentOverrideContext.bindingContext.model) {
				this.model = overrideContext.parentOverrideContext.bindingContext.model; {
					console.log("client-detail-MODEL 3: ", this.model);
				}
			}
			this.jobsDataset = this.model.jobs
			console.log("jobsDataset:", this.jobsDataset)
		}

		aureliaGridReady(aureliaGrid: AureliaGridInstance) {
			this.aureliaGrid = aureliaGrid;
		}

		defineGrid() {
			this.columnDefinitions = [
				{
					id: 'jobNo', name: 'Job No.', field: 'jobNo',
					cssClass: "sg-column-centered",
					maxWidth: 80,
				},
				{
					id: 'agentJobNo', name: 'Agent Job No.', field: 'agentJobNo', cssClass: "sg-column-centered",
					maxWidth: 100,
				},
				{
					id: 'jobType', name: 'Job Description', field: 'jobType',
				},
				{
					id: 'status', name: 'Status', field: 'status',
				},
				{ id: 'companyName', name: 'Company Name', field: 'companyName', sortable: true, type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput } },
				{
					id: 'isWarranty', name: 'Warranty Job?', field: 'isWarranty', cssClass: "sg-column-centered",
					maxWidth: 80,
					formatter: Formatters.checkmark,
				},
				//{ id: 'displayName', name: 'Contact Name', field: 'displayName', sortable: true, type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput } },
				{
					id: 'jobVisits', name: 'Job Visits.', field: 'jobVisits',
					maxWidth: 100,
					cssClass: "sg-column-centered",
				}
			];

			this.gridOptions = {
				autoHeight: true,
				enableAutoResize: true,
				autoResize: {
					containerId: 'sljb-container',
					sidePadding: 15
				},
				enableCellNavigation: true,

				enableRowSelection: true,
				rowSelectionOptions: {
					selectActiveRow: true
				},
			};
		}
	}
```

here is the template:

```
<template>
	<div class="container-fluid">
		<div class="row reduceFont">
			<div class="col-4 border-right">
				<h6>Client Details</h6>
				<div class="card">
					<div class="card-body">
						<address>
							<strong>Full Name:</strong><br>
							<b>${model.clientLastName}</b>, ${model.clientFirstName}<br />
							<br />
							<strong>Address:</strong><br>
							${model.address.address1}<br>
							<!--<span if.bind=${model.address.address2}>${model.address.address2}</span>-->
							${model.address.suburb.suburbName} ${model.address.suburb.postCode}<br>
							${model.address.suburb.state.stateShortName}<br>
							<br />
							<strong>Phone:</strong><br>
							${model.mobilePhone}<br>
						</address>
					</div>
				</div>
			</div>
			<div class="col-8">
				<h6>Jobs</h6>
				<div id="sljb-container">
					<aurelia-slickgrid column-definitions.bind="columnDefinitions"
						grid-options.bind="gridOptions"
						dataset.bind="jobsDataset">
					</aurelia-slickgrid>
				</div>
			</div>
		</div>
	</div>
</template>
```

The next pic shows that I do receive the data but as you can see no grid in the detail view.
![detailView](https://user-images.githubusercontent.com/16522902/65381048-ccc05600-dd2b-11e9-9bcb-82ff8661a63d.png)

The final pic shows the inspection of the grid via  the inspection tools; shows that the grid is indeed being created but I suspect not initiated. It also shows the detail in the Aurelia Inspector showing the data there and other Slick grid items..
![detailView2](https://user-images.githubusercontent.com/16522902/65381104-3e4cd400-dd2d-11e9-9d0f-09ad0427deba.png)

This may be a really simple fix but how do you display a grid in the detail view?

**Comment by ghiscoding** [comment]
Probably the same as this Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/181), the thing is that the Row Detail plugin was never designed to show a grid in a grid, it was designed to show more details about a row (hence the name Row Detail plugin). I don't really have time to troubleshoot such thing, it might be doable but again it wasn't designed for that. There's mainly 2 things that I see as possible problems, 
1. SlickGrid always had issues when adding it to a hidden div container (and that is exactly what that is when the Row Detail panel is closed. SlickGrid requires the div to be shown so it can calculate its viewport size and other things, when the div is hidden it cannot calculate
2. Each grid must have its own grid id and must be unique

There might be ways to go around number 1, but you'll need to search the internet for that. If you find the resolution then please share it and we can update the demo

**Comment by si2030** [comment]
Yep thats most probably the issue.. fortunately the grid in the row detail for me does not need to be complex.. quite the opposite.. so I just built a table with repeat.for and it works... 

I confess I am not up to your level of programming prowess but if I find something on this as I move forward I will let you know..
