### ISSUE TITLE
system-js demo

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#240]
### Your Environment

| Operating System  | windows 10
| NPM/Node/Yarn     |  6.7.0 / 11.10.0

### Context
trying  to run demo for system js

### Current Behavior
missing libraries
### Possible Solution
npm install --save i18next  aurelia-i18n i18next-xhr-backend fn
### errors on au run
au run
Local aurelia-cli v1.2.1
Starting 'readProjectConfiguration'...
INFO [Bundle] Manually adding package: 2.3.3      aurelia-bootstrapper
INFO [Bundle] Manually adding package: 1.0.3      aurelia-event-aggregator
INFO [Bundle] Manually adding package: 1.2.1      aurelia-loader-default
INFO [Bundle] Manually adding package: 1.8.1      aurelia-pal-browser
INFO [Bundle] Manually adding package: 1.3.4      aurelia-polyfills
INFO [Bundle] Manually adding package: 3.4.1      jquery
INFO [Bundle] Manually adding package: 2.24.0     moment
INFO [Bundle] Manually adding package: 1.0.2      text-encoding-utf-8
INFO [Bundle] Manually adding package: 3.4.1      bootstrap
INFO [Bundle] Manually adding package: 1.0.0      aurelia-testing
INFO [Bundle] Manually adding package: 17.3.0     i18next
INFO [Bundle] Manually adding package: 2.3.2      aurelia-i18n
INFO [Bundle] Manually adding package: 3.2.0      i18next-xhr-backend
INFO [Bundle] Manually adding package: 4.6.3      flatpickr
INFO [Bundle] Manually adding package: 4.5.0      lodash.isequal
INFO [Bundle] Manually adding package: 2.14.0     multiple-select
INFO [Bundle] Manually adding package: 2.14.0     aurelia-slickgrid
INFO [Bundle] Manually adding package: 2.4.14     slick-gridmenu
INFO [Bundle] Manually adding package: 1.12.1     jquery-ui-dist
INFO [Bundle] Manually adding package: 2.4.14     slickgrid
INFO [Bundle] Manually adding package: 1.0.11     dompurify
INFO [Bundle] Manually adding package: 0.0.11     text
Finished 'readProjectConfiguration'
Starting 'processMarkup'...
Starting 'processJson'...
Starting 'processCSS'...
Starting 'copyFiles'...
Starting 'configureEnvironment'...
Finished 'processCSS'
Finished 'configureEnvironment'
Starting 'buildJavaScript'...
Finished 'processJson'
Finished 'processMarkup'
Finished 'copyFiles'
Finished 'buildJavaScript'
Starting 'writeBundles'...
INFO [Bundler] Tracing files ...
INFO [Bundler] Auto tracing package: 1.3.1      aurelia-framework
INFO [Bundler] Auto tracing package: 1.4.0      aurelia-history-browser
INFO [Bundler] Auto tracing package: 1.3.1      aurelia-http-client
INFO [Bundler] Auto tracing package: 1.0.2      aurelia-loader
INFO [Bundler] Auto tracing package: 1.5.2      aurelia-logging
INFO [Bundler] Auto tracing package: 1.1.1      aurelia-logging-console
INFO [Bundler] Auto tracing package: 1.0.6      aurelia-metadata
INFO [Bundler] Auto tracing package: 1.8.2      aurelia-pal
INFO [Bundler] Auto tracing package: 1.10.2     aurelia-templating
INFO [Bundler] Auto tracing package: 1.5.3      aurelia-templating-binding
INFO [Bundler] Auto tracing package: 1.12.0     aurelia-templating-resources
INFO [Bundler] Auto tracing package: 1.4.0      aurelia-templating-router
INFO [Bundler] Auto tracing package: 3.3.2      core-js
WARN [PackageAnalyzer] The "font-awesome" package has no valid main file, fall back to index.js.
INFO [Bundler] Auto tracing package: 4.7.0      font-awesome
INFO [Bundler] Auto tracing package: 0.13.2     regenerator-runtime
INFO [Bundler] Auto tracing package: 2.5.0      aurelia-binding
INFO [Bundler] Auto tracing package: 1.5.1      aurelia-dependency-injection
INFO [Bundler] Auto tracing package: 1.2.1      aurelia-history
INFO [Bundler] Auto tracing package: 1.1.5      aurelia-path
INFO [Bundler] Auto tracing package: 1.7.1      aurelia-router
INFO [Bundler] Auto tracing package: 1.3.3      aurelia-task-queue
INFO [Bundler] Auto tracing package: 1.3.2      aurelia-route-recognizer
INFO [Bundler] Auto tracing package: 1.0.3      excel-builder-webpack
INFO [Bundler] Auto tracing package: 2.22.1     moment-mini
INFO [Bundler] Auto tracing package: 3.1.3      jszip
INFO [Bundler] Auto tracing package: 4.17.15    lodash
INFO [Bundler] Auto tracing package: 1.5.1      q
INFO [Bundler] Auto tracing package: 3.1.1      lie
ERROR [DependencyInclusion] Error: could not find "library/fn/set-immediate" in package core-js
INFO [Bundler] Auto tracing package: 3.0.6      immediate
INFO [Bundler] Auto stubbing module: stream
INFO [Bundler] Auto tracing package: 3.0.0      events
INFO [Bundler] Auto tracing package: 2.0.4      inherits
INFO [Bundler] Auto tracing package: 2.3.6      readable-stream
INFO [Bundler] Auto tracing package: 0.11.1     util
INFO [Bundler] Auto tracing package: 1.0.10     pako
INFO [Bundler] Auto tracing package: 1.0.2      core-util-is
INFO [Bundler] Auto tracing package: 1.0.0      isarray
INFO [Bundler] Auto tracing package: 2.0.1      process-nextick-args
INFO [Bundler] Auto tracing package: 5.1.2      safe-buffer
INFO [Bundler] Auto tracing package: 1.1.1      string_decoder
INFO [Bundler] Auto tracing package: 1.0.2      util-deprecate
INFO [Bundler] Auto tracing package: 4.9.1      buffer
INFO [Bundler] Auto tracing package: 1.3.1      base64-js
INFO [Bundler] Auto tracing package: 1.1.13     ieee754
INFO [Bundle] Writing app-bundle.js...
INFO [Bundle] Writing vendor-bundle.js...
Finished 'writeBundles'
Application Available At: http://localhost:9000
BrowserSync Available At: http://localhost:3001

### in browser
system.js:4 Uncaught (in promise) TypeError: Drawing is not a constructor
    at Object.<anonymous> (Picture.js:14)
    at r (system.js:4)
    at T (system.js:4)
    at T.h (system.js:4)
    at T (system.js:4)
    at T.h (system.js:4)
    at T (system.js:4)
    at T.h (system.js:4)
    at T (system.js:4)
    at T.h (system.js:4)

**Comment by ghiscoding** [comment]
The latest version added the new feature of Excel Export. This new feature requires `excel-builder-webpack` which itself requires `lodash` and `jszip`. The error you have about `Drawing not a constructor` most probably comes from `excel-builder`. You'll need to find the proper RequireJS or SystemJS import required for this to work, once you find them you can post them on and I'll update the HOWTO. The other option that you have is to install previous version of Aurelia-Slickgrid `2.13.x` and miss the Excel Export feature. 

Sorry I can't help more than that, I find that supporting all of these other bundlers is starting to be a pain in the... I use only WebPack myself.

**Comment by johntom** [comment]
Thanks for prompt reply, i've tried a few unsuccessful attempts. Will keep you posted if successful. Also having issues running webpack  bs3/bs4 and I added what seems to be missing.
npm install --save nps nps-utils.
Will try adding grid to ew cli nav app next.

**Comment by ghiscoding** [comment]
hmmm `nps` is used by the VSCode Tasks, it should be under the `devDepencies` but not required outside of the Task (I think, though I could be wrong). I don't have much time to test the entire set of Bundlers but I do maintain WebPack since that is the one I use regularly. The best thing about WebPack is that you don't have to care about importing anything, just `npm install` and run, while with RequireJS/SystemJS, that's another much bigger story (finding which modules to add in your `aurelia.json` is painful as can be seen in the [HOWTO](https://github.com/ghiscoding/aurelia-slickgrid/wiki/HOWTO--Step-by-Step#2-for-aurelia-cli-modify-the-aureliajson-file)).

**Comment by johntom** [comment]
I use Frontend creator and with current version depending on systemjs, but the future looks brighter with Aurelia Script and Matt Duffield has many changes in the works...
To be clear I just did an npm install in the D:\Frameworks\slickGrid\aurelia-slickgrid-demos\webpack-bs4-demo directory and then npm start.
```
D:\Frameworks\slickGrid\aurelia-slickgrid-demos\webpack-bs4-demo> npm start

> test-aurelia-new@2.0.0 start D:\Frameworks\slickGrid\aurelia-slickgrid-demos\webpack-bs4-demo
> nps

'nps' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-aurelia-new@2.0.0 start: `nps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-aurelia-new@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\john\AppData\Roaming\npm-cache\_logs\2019-10-22T18_56_18_599Z-debug.log
PS D:\Frameworks\slickGrid\aurelia-slickgrid-demos\webpack-bs4-demo>

```

**Comment by ghiscoding** [comment]
I remember `nps` used to be missing from new project created by the Aurelia CLI. You manually add it to your project is that is still the case and it should be fine after. That is not a problem from Aurelia-Slickgrid but more of a problem from the CLI itself, have you updated your CLI to the latest? I really thought that was fixed in the CLI

**Comment by johntom** [comment]
Changing the following in package.json fixed issues with system.js demo. Will work on config for 2.14.0 and get back asap. Thanks and since I need to export I will try!
```
"dependencies": {
    "aurelia-animator-css": "^1.0.4",
    "aurelia-bootstrapper": "^2.3.2",
    "aurelia-fetch-client": "^1.0.0",
    "aurelia-http-client": "^1.2.1",
    "aurelia-i18n": "^2.3.2",
    "aurelia-slickgrid": "^2.13.5",
...
  },
  "devDependencies": {
    "aurelia-cli": "^1.0.2",

```

**Comment by ghiscoding** [comment]
Thanks I will look into updating in coming days. Feel free to share if there's anything else to change and thanks for the feedback

**Comment by ghiscoding** [comment]
This is what you need to get RequireJS/SystemJS builds to work, you need to add the following to your `aurelia.json`

```json
{
  "name": "jszip",
  "path": "../node_modules/jszip/dist",
  "main": "jszip.min"
},
{
  "name": "excel-builder-webpack",
  "path": "../node_modules/excel-builder-webpack",
  "main": "src/excel-builder",
  "deps": [
    "jszip",
    "lodash"
  ]
}
```

The [HOWTO](https://github.com/ghiscoding/aurelia-slickgrid/wiki/HOWTO--Step-by-Step) Wiki was updated with this new info. You can also see this [commit](https://github.com/ghiscoding/aurelia-slickgrid-demos/commit/b4e9299a74461fa1edce89b9537e319dff19ad04) to fix the Aurelia-Slickgrid-demos.

**NOTE** 

However please note that the Excel Export still doesn't work for unknown reasons. The pages finally load but the Excel Export throws some errors saying `ExcelBuilder.Workbook is not a constructor` but again that works fine in WebPack. So I don't know why it doesn't work in SystemJS but I disabled `enableExcelExport: true` and instead use the CSV Export via `enableExport: true`, that is the best I can do. Basically I got it working in SystemJS but if you want the real Excel Export then please use WebPack bundler, I won't spend more time on this.
