### ISSUE TITLE
Checkbox Column Filter on Text

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#241]
Hi,
Making good progress in testing grid as I'm looking to replace kendo-ui grid. Is there a way to have a a column checlbox for text values as demonstrated in 4-Client Side Sort/Filter? In my case I'd like to show all the artists names as the filter.  The grid will have a unique artist in each row. I only see examples of boolean and number types using this technique.
John

**Comment by ghiscoding** [comment]
I created ton of Wikis, I suggest you read them, in your case [Select Filter](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Select-Filter)
