### ISSUE TITLE
Checkbox Column Filter 

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#243]
Hi,
This is not a bug.
I had started to read the wikis and they are excellent.
In my case I was able to get filtering to work in all 3 ways
1) have the dataset populated in a service so when I open form the dataset is available
constructor(http,appService) {
        this.http = http;
        this.appService = appService;
        this.names=  this.appService.artistnams

  collection: this.names,
               

2) use the   collectionAsync: this.http.fetch(' https://website.com/api/v1/artistnames')

3) collectionAsync :this,getNames(),
 async getnames() {
        var url = 'https://website.com/api/v1/artistnames'
        let response = await this.getArtists(url);
        return  response  
    }
    async getArtists(url) {
        let res = await this.http.fetch(url, { mode: 'cors' }).then((res) => res.json())
        return res
      }

This grid with aurelia is first class!
John

**Comment by ghiscoding** [comment]
> In my case I was able to get filtering to work in all 3 ways

If it works in all 3 ways then why are you opening an issue? Unless you mean the inverse that it doesn't work.

There's plenty of examples with `collectionAsync`, take the [Example 3](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/examples/slickgrid/example3.ts) for a start, it works with local JSON files, I showed examples for both the regular http and fetch. The thing I can say is, don't put `await` in front of any of them, the lib will deal with it itself internally. Also you're most probably have CORS issues and that has nothing to do with the lib.

**Comment by johntom** [comment]
Sorry originally had an issue corrected the text and just thought I’d
share.

**Comment by ghiscoding** [comment]
So it's not an issue anymore and we can close it then?

**Comment by johntom** [comment]
Yes

**Comment by ghiscoding** [comment]
I'm not sure if you saw my message after I edited but I was saying... If you want me to update some of the Wikis, tell me the link and the text you want to modify and I'll update them

**Comment by johntom** [comment]
WIll do!
