### ISSUE TITLE
Embeded Object

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#244]
"aurelia-slickgrid": "^2.13.5",
Hi,
The documentation clearly shows how to display complex objects 
```
this.columnDefinitions = [
  {
    // the zip is a property of a complex object which is under the "buyer" property
    // it will use the "field" property to explode (from "." notation) and find the child value
    id: 'zip', name: 'ZIP', field: 'buyer.address.zip', filterable: true
   // id: 'street',  ...
];
```
```
I have the following in my collection
{
ID: 19823,
OwnerID: "5d7e63267a045b44755c020a",
InventoryCode: "WILLIAMS351",
artist: {
id: "5d63e02d5e9e4aa41e0bea62",
ID: 0,
firstName: "William T.",
lastName: "Williams",
yearofBirth: "1942",
died: "",
ArtistName: "Williams, William T."
},
```
This will display but not filter
```
   {
                id: 'artist',
                name: 'Artist',
                field: 'artist',
                filterable: true,
                sortable: true,
                type: FieldType.string,
                minWidth: 125,
                formatter: function (row, cell, value, columnDef, dataContext) {
                    return value.lastName;
                },
                filter: {
                    model: Filters.input
                }

            },
```
this does not display but filters
```
 {
                id: 'Artistlast', 
                name: 'Artistlast',
                field: 'artist.lastName',
                type: FieldType.string,
                filterable: true
            },
```

**Comment by ghiscoding** [comment]
You need to use `formatter: Formatters.complexObject` in your column definition when dealing with complex objects.

**Comment by johntom** [comment]
Thanks,
I took a deep dive and acomplised many items on tick list be reading the wiki and following the examples. I even created an detail image viewer to display image on row( see below). All column filters represent unique values of the column in grid which was I understood the model provides a fantastic level of control.



![image](https://user-images.githubusercontent.com/1877376/67626111-fc73e980-f814-11e9-8a09-52c3d38fc345.png)

**Comment by ghiscoding** [comment]
> Is there a way to enlarge the height of detail panel?

```ts
rowDetailView: {
        // how many grid rows do we want to use for the row detail panel (this is only set once and will be used for all row detail)
        // also note that the detail view adds an extra 1 row for padding purposes
        // so if you choose 4 panelRows, the display will in fact use 5 rows
        panelRows: this.detailViewRowCount,
```

> I've seen the hover tooltip feature (https://mleibman.github.io/SlickGrid/examples/example-autotooltips.html) will display text thats wider than column.

```ts
    this.gridOptions = {
      enableAutoTooltip: true,
   }
```

> Is there an example of the tooltip data plugin. Would also like to use the hover to show an enlared image instead of clicking on + detail button.

you can probably do that with a [Custom Formatter](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Formatters#custom-formatter). The `autotooltip` is the same as the one shown in the SlickGrid example you found, it only takes display the text. I personally never use it

> I've been using the commecial version of kendoui and my client did not like it very much and must say I'm finding this superior in many ways,

Thanks I've spent thousand of hours on this for the past 2 years, so I hope it's helpful.

**Comment by johntom** [comment]
helpful? more like awesome!
