### ISSUE TITLE
2.14.0

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#249]
I updated to 2,14,0 today and all the issues with using complex objects with csv exports work as you described so perhaps it was an issue with 2.13.5. I did a sanity test for code below to see it fail.

I want to know if you want me to convert the type script  examples 17 thru 23 to javasscript for system/require js demos.

Export to csv works fine but not to excel (Uncaught (in promise TypeError: ExcelBuilder.Workbook is not a constructor    at excelExport.service.ts:96). I will try to track down but not that important for me at the moment and I did not want to write up a bug report until I test further.

John
```
 {
                id: 'artist', name: 'Artist',
                field: 'artist.ArtistName',
                headerKey: 'Artist',
                sortable: true, minWidth: 100,
                filterable: true,
                exportWithFormatter: true,
                filter: {
                    collection: this.names,
                    model: Filters.multipleSelect,
                    filterOptions: {
                        offsetLeft: 2,// 14,
                        width: 190
                    },
                    placeholder: 'choose an option'
                },
                formatter: Formatters.complexObject ,
               // formatter: this.artistTranslateFormatter, NOT NEEDED FOT 2.14.0
               // params: { useFormatterOuputToFilter: true }
            },
            {
                id: 'MediumSupportobj',
                name: 'MediumSupportobj',
                field: 'MediumSupportobj.Description',
                filterable: true,
                sortable: true,
                type: FieldType.string,
                minWidth: 125,
                exportWithFormatter: true,
                filter: {
                    collection: this.medium,
                    model: Filters.multipleSelect,
                    filterOptions: {
                        offsetLeft: 2,// 14,
                        width: 190
                    },
                    placeholder: 'choose an option'
                },
                formatter: Formatters.complexObject ,
            },
```

**Comment by ghiscoding** [comment]
I believe I fixed Excel Builder but I didn't release a new version yet, I'm trying to finish all the Aurelia-Slickgrid unit tests before release a new version. Here's the [commit](https://github.com/ghiscoding/aurelia-slickgrid/commit/b992187f346cf432ff91c00f78d6a1df9ad31ac9) of the fix anyway

**Comment by ghiscoding** [comment]
I just accomplished full test coverage today (99%) and that was the last thing I wanted to do before releasing the new version [2.14.1](https://github.com/ghiscoding/aurelia-slickgrid/releases/tag/v2.14.1) is out and includes the fixes of Excel Export for RequireJS/SystemJS bundle. 

So I'll close this issue, it should be all good now.
