### ISSUE TITLE
[bug]: findOrDefault shows in mergeGridOptions which uses jQuery extend

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/aurelia-slickgrid#27]
**I'm submitting a bug report**

* **Bundler used (WebPack/RequireJS/SystemJS**
WebPack

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
Aurelia-Slickgrid `mergeOptions` function uses jQuery `$.extend()` and for some reasons the Grid Presets which before the merge has a valid array of objects, has the object replaced by a `findOrDefault` function.

**Expected/desired behavior:**

* **What is the expected behavior?**
No error and no Array prototype function

**Comment by ghiscoding** [comment]
@jmzagorski 
Can you look into this? The function `findOrDefault` which you added is causing some issues after merging the grid options. I'm actually not sure that this is a good idea to make it available on the `Array.prototype`, it seems that jQuery `$.extend` uses that too. This problem only seem to show in Example 5 (Grid with OData Service). Even though the function might be convenient to on the `Array.prototype`, it is nonetheless dangerous to overwrite any prototype function. I have been been hit by doing that in the past too.

**Comment by jmzagorski** [comment]
So `findOrDefault` is already a function in the jQuery library?

**Comment by ghiscoding** [comment]
I don't think `findOrDefault` is a jQuery function but for unknown reason it does affect the merge. And yes I would rather make it a simple utility function, to avoid having side effects like this bug. 

Plain old javascript is ok when it's simple but creating an element without jQuery is kinda long. The other convenience of jQuery is that it returns `null` if it doesn't find an element, while in plain javascript it will crash unless you handle with try/catch. However I think Aurelia has a couple of utilities to deal with the DOM. I just tend to go with jQuery since it's already available and it works in both of my repos (Angular/Aurelia) but I don't mind to go with plain js if it's not too long

**Comment by jmzagorski** [comment]
It looks like since you are performing a deep merge, and for some reason jquery is not performing the logic `if (object.hasOwnProperty(propName))` during the object  property iteration, it gets attached as a property to the filters. I am working on this fix now
