### ISSUE TITLE
aurelia slickgrid without aurelia

### ISSUE THREAD

**Issue by michaelongithub** [ghiscoding/aurelia-slickgrid#273]
Can it be used without aurelia ?
Like in basic js / ts app without any framework.
Like just reference it with
1 (possibly some more) js / ts file
1 (possibly some more) css file
in the header of page
only dependency jquery.
no precompiles build ect

Thanks for info, would be great, Michael

**Comment by ghiscoding** [comment]
This is an Aurelia specific library, if you want to use vanilla JavaScript then use the [SlickGrid](https://github.com/6pac/SlickGrid/) core library.

**Comment by ghiscoding** [comment]
@michaelongithub 
Coming back on this issue, when I replied earlier it wasn't possible to use it without Aurelia-Slickgrid but that is no longer the case, I created a new lib called [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) which works with plain TypeScript/JavaScript. There's also a demo site, so if you're still interested, I'm planning an official release sometime this week or next week.

**Comment by michaelongithub** [comment]
Great, thanks a lot, will check it out.
Cheers, Michael
