### ISSUE TITLE
Semantic-UI theme

### ISSUE THREAD

**Issue by PraveenGandhi** [ghiscoding/aurelia-slickgrid#277]
Thank you for your good work. Is there a simple way to use with semantic-ui. If it is simple, please let me know where to start.
Please share your inputs.

Thank you.

**Comment by ghiscoding** [comment]
This lib is made with and for Bootstrap, I know nothing about Semantic UI but the only thing I could say is that I mentioned in the readme that you can make your own theme by the use of the SASS variables (there's now ~400). So, for example you could make it look like Material Design if you wish but it might break in some areas like the Compound Filters but for the rest it should work.

**Comment by PraveenGandhi** [comment]
Thank you for your reply. Let me try and see if this easy to use with semantic ui early next year. Happy new year.

**Comment by ghiscoding** [comment]
Thanks, if you want to contribute a different theme, I'd be happy to receive a PR for that. Happy Holidays

**Comment by ghiscoding** [comment]
To expand on this issue a little bit, I've recently added 2 new themes (Material Design & Salesforce), if anyone wishes to create another theme, you can simply copy the [slickgrid-theme-material.scss](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/styles/slickgrid-theme-material.scss) and update necessary SASS variables. These 2 new themes also work without Bootstrap, for example my new lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) uses [Bulma](https://bulma.io/)

So all that to say, if anyone wants to create new Theme(s), it should be quite easy now that there are 3 Themes that already exists.
