### ISSUE TITLE
no such method 'dispose', 'show'

### ISSUE THREAD

**Issue by jbockle** [ghiscoding/aurelia-slickgrid#293]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Aurelia           |  1.3.1 |
| Aurelia-Slickgrid | 2.16.1 |
| TypeScript        |  3.7.3 | 
| Operating System  | windows | 
| NPM/Node/Yarn     | 6.13.4, 12.14 |

### Context
bootstrap components with same jquery-ui signature (like tooltips) outside slickgrid cannot access methods overridden by jquery-ui

### Expected Behavior
$('.tooltip').tooltip('dispose') disposes the bootstrap tooltip

### Current Behavior
an error is shown in console `no such method 'dispose' for tooltip widget instance`

### Possible Solution
remove import of jquery-ui in 'aurelia-slickgrid.ts' so that the consuming application can control the order of imports and use the bootstrap jquery extension methods instead
see https://stackoverflow.com/questions/17458224/uncaught-error-no-such-method-show-for-tooltip-widget-instance

**Comment by ghiscoding** [comment]
I cannot remove jQuery-UI, it's a dependency of SlickGrid and since it's a dependency, I'm also using it for the Autocomplete Filter and the Compound Slider Filter. So you'll have to find another way to do what you want. in our project, we use jQuery Tipsy (which Bootstrap tooltip is based of).

**Comment by ghiscoding** [comment]
Also just to confirm, I tried removing the import of jQuery UI and I get the following error from SlickGrid (core). 
```bash
SlickGrid's 'enableColumnReorder = true' option requires jquery-ui.sortable module to be loaded
```

The only thing that I could think of would be to add a flag in the grid options to disable the import and I could dynamically load it later, like I did [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/extensions/extensionUtility.ts#L29) for the extensiosn, BUT grid options like the `enableColumnReorder` is there from the start and dynamically changing grid options after the grid is loaded is not recommended and just updating the `enableColumnReorder` (and possibly a few other grid options) is kind of a bummer to do. 

So I don't see any other viable solution, jquery-ui is just part of SlickGrid and it's hard to go without

**Comment by jbockle** [comment]
Right, not suggesting to remove the dependency, just suggesting to remove the import so that the consuming app can import it after importing bootstrap's js.

**Comment by ghiscoding** [comment]
Unfortunately I can't because of the error that throws out in the console, SlickGrid just doesn't like to be without it. Have you tried importing Bootstrap after Aurelia-Slickgrid?

**Comment by jbockle** [comment]
I understand, thanks
