### ISSUE TITLE
[release 1.9.x] - post release feedback

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/aurelia-slickgrid#30]
@jmzagorski 
Opening this simply for reference and discussions about latest version `1.9.0`
1. Jumped over `1.8.0`, I'm so used to updating the `package.json` directly for the version that I forgot that isn't needed anymore, which explain the jump.
2. Have you started using WebPack 4? I see the [Aurelia-CLI](https://github.com/aurelia/cli/commit/5838e15ccf6a0891da7d4d7ecb6c8d5b98414a43) got some commit around it
3. I'm having some issues with the Build of Github Page, have you ever seen this problem? There's no double quotes on any of the scrips `src` or css `href`. That is causing some issues with the demo, until I change them all (by hand) to be wrapper in double quotes. 
   1. I have tried to update a few of the Aurelia lib but that doesn't seem to do any changes
   2. could it be the [webpack.config](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/doc/github-demo/webpack.config.js)?

![quotes](https://user-images.githubusercontent.com/643976/37321628-84aaa2c4-264f-11e8-98ee-385e29d2bc5d.png)

**Comment by jmzagorski** [comment]
>  Have you started using WebPack 4? I see the Aurelia-CLI got some commit around it

I am still on "webpack": "^2.6.1", :-(. I realllly need to update, but I have been so involved with getting my application updated to version 2.0, updating webpack has been an afterthought.

>I'm having some issues with the Build of Github Page, have you ever seen this problem?

I have never seen that before, probably because I am so behind on updating my builds. What file has those `src` and `href` without quotes?

**Comment by ghiscoding** [comment]
Side note, I have now released Compound Filter in my Angular repo, you can see a demo of it [there](https://ghiscoding.github.io/Angular-Slickgrid/#/clientside), lovin' it  hehe
