### ISSUE TITLE
the highlight row in example20

### ISSUE THREAD

**Issue by crazy365966834** [ghiscoding/aurelia-slickgrid#301]
In the example20, https://ghiscoding.github.io/aurelia-slickgrid-demos/#/slickgrid/example20
when mouse hover at one row ,then highlight background color only show by one side, and another is the same as usual. 
I know that here is using hover to show highlight color.

can fix this question? 
such as mousein/mouseout

**Comment by ghiscoding** [comment]
You can try some of this [CSS styles](https://github.com/6pac/SlickGrid/blob/master/examples/example-frozen-columns.html#L12) from this SlickGrid [Example](https://6pac.github.io/SlickGrid/examples/example-frozen-columns.html)

**Comment by ghiscoding** [comment]
Taking a quick look at it, this [line](https://github.com/6pac/SlickGrid/blob/master/examples/example-frozen-columns.html#L274) is what does the trick. We can use the row selection to show a highlight of current row and remove the selection (highlight) when no longer on that row.

So if you update your code with the following code that will work, there's no code to change in the lib itself.
```ts
aureliaGridReady(aureliaGrid: AureliaGridInstance) {
    const grid = aureliaGrid.slickGrid;

    // with frozen grid, in order to see the entire row being highlighted when hovering
    // we need to do some extra tricks (that is because frozen grids have 2 separate div containers)
    // our tricks is use row selection to highlight when hovering and remove the selection once we're not
   grid.onMouseEnter.subscribe((e) => {
      const cell = grid.getCellFromEvent(e);
      grid.setSelectedRows([cell.row]); // highlight current row
      e.preventDefault();
    });
    grid.onMouseLeave.subscribe((e) => {
      grid.setSelectedRows([]); // remove highlight
      e.preventDefault();
    });
  }
```

**Comment by crazy365966834** [comment]
It's work, thanks.

**Comment by ghiscoding** [comment]
The demo is updated with the new code provided. 

Please upvote if you like the lib, thanks ⭐️
