### ISSUE TITLE
Pinned (frozen) Columns for the first and last

### ISSUE THREAD

**Issue by crazy365966834** [ghiscoding/aurelia-slickgrid#302]
In the example20, https://ghiscoding.github.io/aurelia-slickgrid-demos/#/slickgrid/example20
the example pinned left two columns,
can I pinned the first column and the last column?
like this:
https://ant.design/components/table-cn/#components-table-demo-fixed-columns

**Comment by ghiscoding** [comment]
No there's only the left side that can be pinned, see this [issue](https://github.com/6pac/SlickGrid/issues/410) for reference.
