### ISSUE TITLE
[feature] - automatically adjust multiple-select dropup or dropdown by available space

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/aurelia-slickgrid#34]
**I'm submitting a feature request**

**Current behavior:**
Always show as a dropdown

**Expected/desired behavior:**

* **What is the expected behavior?**
Use as a dropup (going up) or dropdown (going down which is the default)

* **What is the motivation / use case for changing the behavior?**
More user friendly UI

**Comment by ghiscoding** [comment]
@jmzagorski 
Do you want to give this a shot? I know you made and probably are using the multiple-select with Editor. I created today in my Angular project a component to also use `multiple-select.js` and found how to automatically use dropup or dropdown with the following code

```javascript
onOpen: () => {
        const selectElmHeight = 32; // height in pixel of the multiple-select element

        const windowHeight = $(window).innerHeight();
        const pageScroll = $('body').scrollTop();
        const offset = $(this.el.nativeElement).offset().top;
        const space = windowHeight - ( offset - pageScroll );
        const $msDrop = $(this.el.nativeElement).find('.ms-drop');

        if ( space < ($msDrop.height() + selectElmHeight) ) {
            $msDrop.addClass('top');
            $msDrop.removeClass('bottom');
          } else  {
            $msDrop.addClass('bottom');
            $msDrop.removeClass('top');
        }
      },
```

The only piece of code to replace (from Angular to Aurelia) is the select container, so basically this `$(this.el.nativeElement)` should be replaced by `this.$editorElm`. I think that would work but I haven't tested it. I'm not using inline editors but you are, so this might be interesting. I might end up putting in in the Filters as well, seems easy enough

**Comment by jmzagorski** [comment]
yup i can look into this. I _hope_ to finish my API that will be feeding my grid this week, so I can start right after (or i can fit it in between if I have time too)

**Comment by ghiscoding** [comment]
@jmzagorski 
I forgot to create a new branch before doing the commit push and so I can't do a PR anymore. However you can review the code. Works great on my side and I did a build test as well.

**Comment by jmzagorski** [comment]
okay, thanks for doing this. I have a tight deadline for next week and still working on the API. I expect to the get back to my grid soon since I will need to complete my client changes before my app's beta release next week.
