### ISSUE TITLE
Some translations are not using namespace prefix

### ISSUE THREAD

**Issue by jani-pernu** [ghiscoding/aurelia-slickgrid#346]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Aurelia           | 0.6.0
| Aurelia-Slickgrid | 2.18.1
| TypeScript        | 3.8.2
| Operating System  | Win10
| NPM/Node/Yarn     | 6.13.4/13.5.0.

### Context

Use separate (non-default) namespace for translations required by aurelia-slickgrid
e.g. "aurelia-slickgrid.json"

### Expected Behavior

All translations should work when translation namespace is defined in grid options

### Current Behavior

Following lines are printed to console when i18n debug is enabled
1. No namespace utilization at all

> i18next::translator: missingKey fi common ITEMS ITEMS logger.js:24:62
> i18next::translator: missingKey fi common OF OF logger.js:24:62
> i18next::translator: missingKey fi common ITEMS ITEMS logger.js:24:62
> i18next::translator: missingKey fi common OF OF logger.js:24:62

2. No namespace separator utilization with the default separator
These ones are fixed by explicitly also defining the separator in grid options

> i18next::translator: missingKey fi common aurelia-slickgridITEMS_PER_PAGE aurelia-slickgridITEMS_PER_PAGE logger.js:24:62
> i18next::translator: missingKey fi common aurelia-slickgridITEMS aurelia-slickgridITEMS logger.js:24:62
> i18next::translator: missingKey fi common aurelia-slickgridOF aurelia-slickgridOF logger.js:24:62
> i18next::translator: missingKey fi common aurelia-slickgridPAGE aurelia-slickgridPAGE

Other translations work correctly and are displayed in the grid

### Code Sample
```
this.gridOptions = {
	enableTranslate: true,
	translationNamespace: "aurelia-slickgrid",
	translationNamespaceSeparator: ":",
	params: { i18n: this.i18n }
} as GridOption;
```

**Comment by ghiscoding** [comment]
I don't want to spend more time on this, I hope that you can contribute on this one because I don't like working on something that I'll never use.

**Comment by ghiscoding** [comment]
@jani-pernu 
Will you be able to help in fixing this issue? If not, I'm afraid this issue will remain open indefinitely.

**Comment by jani-pernu** [comment]
Currently unfortunately no, I've got my hands full at integrating this grid to our project.
In the future maybe but not likely :)
This is not a major issue as most of the translations now work.
Column name translations don't work (from custom namespace) but I worked it out by translating those manually in the column definitions.

**Comment by ghiscoding** [comment]
Since I don't see any potential help on this issue, neither it being a huge problem anymore, I would rather just close it. I can reopen if anyone is willing to help
