### ISSUE TITLE
Text Filter is lost of focus when "suppressActiveCellChangeOnEdit = false"

### ISSUE THREAD

**Issue by Ischca** [ghiscoding/aurelia-slickgrid#381]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Aurelia           | 1.3.1|
| Aurelia-Slickgrid | 2.19.0|
| TypeScript        | 3.9.5 |
| Operating System  | Windows 10 |
| NPM/Node/Yarn     | Yarn 1.22.4 |

### Context

Focus is lost while inputting filter.

### Expected Behavior

Focus is not lost while inputting filter.

### Current Behavior

1. Set config `suppressActiveCellChangeOnEdit = false`.
1. Click on the any cell to activate it.
1. Enter any text in the text filter.

### Code Sample

Reproduce in example 26.
https://ghiscoding.github.io/aurelia-slickgrid/#/slickgrid/example26

**Comment by ghiscoding** [comment]
not sure to understand your problem I've never seen anything like you're saying but I never use that flag `suppressActiveCellChangeOnEdit` and even then that is probably a core lib (SlickGrid) issue not related to Aurelia-Slickgrid

**Comment by Ischca** [comment]
Sorry, my confirmation was insufficient.
I have implemented a behavior that activates the clicked cell and changes the delete flag of the data by the delete button outside the grid.
I used suppressActiveCellChangeOnEdit to find the target to be deleted by the delete button process.

**Comment by ghiscoding** [comment]
eee what's the point of activating the cell if you delete the row from an external delete button? I don't fully understand your behavior, perhaps an animated gif might help (I use [ShareX](https://getsharex.com/) for that on Windows).

I'm sure there's a better approach to avoid having to change this flag. I don't want to spend hours in troubleshooting this issue (unless you want to do it yourself) and again it's a core lib issue, which would have to be fixed there (not Aurelia-Slickgrid related). I don't fully remember why I created this flag but I think it was meant to never be turned off in Aurelia-Slickgrid but to be off in SlickGrid itself to avoid breaking anyone using the core lib except my lib.

**Comment by Ischca** [comment]
Thank you for your kindness.
I created a GIF, but this may not convey the message.
![xODNIa8RIb](https://user-images.githubusercontent.com/38150350/87108143-8331ff00-c29c-11ea-8700-6f045c3f7dbd.gif)

All I want to do is select a row and delete the selected row, `suppressActiveCellChangeOnEdit` is deprecated, I'll try another method It is.

**Comment by ghiscoding** [comment]
Hmm I cannot read this language, Japanese is it?
Why don't you use `onClick` event to keep an array of the selected rows and just delete them whenever you want? Unless I misunderstood what you want to do. Which row are you trying to delete? I don't see any rows being deleted

**Comment by Ischca** [comment]
Sorry, this is in Japanese.
The red button is the delete button and the green button is to confirm the change.
Deleted rows will be grayed out and will remain.
This is because it may be restore it.

What I want to do here is to find the row that for delete when I press the red button.
I don't want to change the current source, so I'll use the `ExcelCopyBuffer` drag instead.
Thank you for your kindness.
