### ISSUE TITLE
Conflict with Froala editor

### ISSUE THREAD

**Issue by haimavni** [ghiscoding/aurelia-slickgrid#48]
**I'm submitting a bug report**

* **Framework Version:**
aurelia cli 0.27.0

**Please tell us about your environment:**
* **Operating System:**
Windows 7 and also Ubuntu 16.04

* **Bundler used RequireJS

* **Browser:**
Chrome
* **Language:**
 TypeScript

The problem is not directly with slickgrid. The problem is that when I add aurelia-slickgrid to the project dependencies, a plugin named aurelia-froala-editor is broken - it does not respond to mouse clicks at all.

**Comment by ghiscoding** [comment]
Unfortunately I don't use that other npm package so you will have to troubleshoot yourself. 
what you can try is to manully delete each javascript file used by `Aurelia-Slickgrid` until you find that your other lib works. For example, you can start by deleting [jquery.event.drag-2.3.0.js](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts#L3) from the `slickgrid` folder. I'm  not sure how good this test will be though because it will probably stop build from the start. so that might be invalid. Anyhow, I don't know what else to try, I can't do much more

**Comment by haimavni** [comment]
Hi Ghislain,

I am writing to you because I find slickedit very attractive and I wish I
could use it in my app.

I had another issue with aurelia-slickedit which is not related to the
other package. Also, the conflict with Froala editor may expose a more
general issue which is worth working on.
If you like to spend some time on these issues, please do the following:

git clone https://github.com/haimavni/test-grid.git
cd test-grid
npm install
au run --watch
In your browser, enter the address localhost:9000

It should not take more than a minute or two.

You will see the table showing nicely, as it should, and the editor is
there but you can not enter text.

If you uncomment the two commented lines in src/example1.html, you will see
that the screen remains empty and inspecting the console shows some error.
May be I am missing something but I don't think this should happen.

Please let me know if there are some (hopefully good) news.

Thanks,

Haim Avni

**Comment by ghiscoding** [comment]
I'm in vacations for 3 weeks so no I won't test it. What I wrote if for you to test it. Please note that this lib is all done through free time and there isn't much more I can do at this point

**Comment by haimavni** [comment]
Have a nice vacation!

בתאריך יום ב׳, 16 באפר׳ 2018, 14:46, מאת Ghislain B. ‏<
notifications@github.com>:

**Comment by jmzagorski** [comment]
@haimavni i don't have a any experience with the aurelia-cli, but if I have time this week I can look into it.

**Comment by ghiscoding** [comment]
@haimavni 
Some news, your problem seems to be related to `jquery dragevent.js` which is what I thought it was. Can you refer to this new issue opened in SlickGrid [issue #239](https://github.com/6pac/SlickGrid/issues/239) and try the option 1 as the user mentioned. 

> I see two possible solutions:
fix jquery.event.drag: make it never return false by removing the return false statement.
				// // helps prevent text selection or scrolling
				// if ( !drag.touched || dd.live )
				//     return false;

**Comment by loonix** [comment]
I made a fork and changed a line to avoid this issue. if you use package.json just add this line in (worked for me in angular):
"slickgrid": "git+https://github.com:loonix/SlickGrid.git",

**Comment by ghiscoding** [comment]
@loonix 
interesting, you commented out the touchstart mousedown `drag.init` but I wonder if certain actions stops working. I'm not sure which functionality uses this, but does the column move still works? That would be the biggest functionality I can think of.

**Comment by loonix** [comment]
Well, after testing for a bit it seems to work with froala but I now can't select the cells for the copy paste. :S

**Comment by ghiscoding** [comment]
The main issue is that jQuery Event doesn't use namespace, so it conflicts with other libraries. Maybe what you can try is to add a prefix to the event name to give a namespace. For example trying adding the prefix on the following 3 lines (82, 97, 122)

```js
$event.add( this, "jquery.touchstart mousedown", drag.init, data );  // 82

$event.remove( this, "jquery.touchstart mousedown", drag.init ); // 97

drag.touched = event.type == 'jquery.touchstart' ? this : null; // 122
```

**Comment by loonix** [comment]
Tried that but now Slickgrid works but froala doesn't

**Comment by ghiscoding** [comment]
I don't know what else to try, I already tried a few things back then, they are mentioned in the core lib repo

> Since there's an [open issue #239](https://github.com/6pac/SlickGrid/issues/239) in `SlickGrid`

**Comment by loonix** [comment]
I think I hacked it, and for what I use SlickGrid and Froala it is working well so far:

https://github.com/loonix/SlickGrid/commit/ff97884a72267c5391724a85ef93c9e1d397139e#diff-28bc52c53e20a72616236359a43571a2

**Comment by ghiscoding** [comment]
@loonix 
The latest SlickGrid version (core) was released including your patch, was there anything special to do apart from updating? I think no, but just making sure. Thanks again

**Comment by ghiscoding** [comment]
Better late than never... I have finally found and fixed the problem in SlickGrid itself with this [PR #454](https://github.com/6pac/SlickGrid/pull/454). Also worth to know that latest version of Froala was working even without a fix, they must have changed somethig since the problem was reported.

**Comment by ghiscoding** [comment]
closed by latest version
