### ISSUE TITLE
gridOptions are out of sync with grid.getOptions()

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#49]
**I'm submitting a bug report**
Maybe this is a bug or maybe you did it by design

* **Framework Version:**
current

**Please tell us about your environment:**
* **Operating System:**
All

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
`GridEventService` passes `grid` and `gridOptions`, but `gridOptions` are out of date.

**Expected/desired behavior:**
`gridOptions` are up to date

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
I was using [attachOnClick](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/services/gridEvent.service.ts#L48) in the `GridEventService` and notice you are passing the `grid` and `gridOptions`. However, if a property on the `gridOptions` are changed after `AureliaSlickgridCustomElement` initializes using `grid.getOptions().fooBar = "new property"`, `grid.getOptions()` will not match `gridOptions` because that `gridOptions` are the original options used in the custom element. `Slickgrid` uses `$.extend{}` to create a copy of the `gridOptions` which is why these are out of sync

I know you are on vacation so don't respond to this :-). There is no rush, I just wanted to submit it as an issue/question before I forgot.

**Comment by ghiscoding** [comment]
Would you be able to make a PR to address it?
