### ISSUE TITLE
Aurelia-slickgrid breaks other jquery references

### ISSUE THREAD

**Issue by rosshigh** [ghiscoding/aurelia-slickgrid#491]
I created a test project to play around with aurelia-slickgrid and all went well.  When I tried to replace aurelia-table with aurelia-slickgrid in an existing project, I seem to have broken all my existing references to jquery.  I was previously loading jquery and bootstrap in the index.ejs file, but if I replace all of that with the method described in the How-to guide, I get a lot of errors like this:

`editPeople.js?803f:60 Uncaught (in promise) TypeError: $(...).selectpicker is not a function
fuelux.js:13 Uncaught ReferenceError: jQuery is not defined`

If I put it back the way it was, I get this:

`Uncaught (in promise) Error: SlickGrid's 'enableColumnReorder = true' option requires jquery-ui.sortable module to be loaded`

Any help would be appreciated.

Ross

**Comment by ghiscoding** [comment]
jQueryUI is also a dependency and the last message suggest you didn't load it.

**Comment by rosshigh** [comment]
That was it!  Thank you.
