### ISSUE TITLE
[Feature]: Add a callback to the CollectionFilterBy model

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#61]
**I'm submitting a feature request**

* **Language:**
TypeScript

**Current behavior:**
The `collectionService` only provides simply filtering on a collection with a `property` and a `value`

**Expected/desired behavior:**

* **What is the expected behavior?**
Add a callback either as the `operator?: OperatorType.equal | OperatorType.notEqual | Function;` or create a separate property called callback.

* **What is the motivation / use case for changing the behavior?**
This will allow for more advanced filtering.

@ghiscoding I wanted your feedback before I started doing this. 1. Do you think this is a good idea and 2 where should i put this `callback` property (and what name do you prefer) on the `CollectionFilterBy` model. I think this will provide more robust filtering when a simple `property` and `value` will not be sufficient.

**Comment by ghiscoding** [comment]
Hmm I'm not sure to understand what you would like to add. When I created that Service, it was to filter a collection and nothing more, that Service shouldn't know about anything else but the collection, I think...

Can you provide a sample of what you're after?

**Comment by jmzagorski** [comment]
On second thought you're right. I looked at  the collection filter service again and one thing is missing that I need, the data item. Basically I need to filter the collection based on the current data context and for some reason I thought i could do that with a callback in your filter collection service.

Just an FYI with what my filtering looks like:

```
this.collection.filter(c => c.roles.find(t =>
        dataContext.jobTitle && t.jobTitleName === dataContext.jobTitle.displayName));
```

In this example I am filtering the collection's inner array to see if the inner array contains the dataContext job title.
