### ISSUE TITLE
DateFilters in filter-conditions leave invalid/null dates in filter

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#68]
**I'm submitting a bug report**
Unless this is by design?

* **Framework Version:**
1.13.0

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
An example is in the dateIsoFilterCondition, which will always filter for invalid dates as coded [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/filter-conditions/dateIsoFilterCondition.ts#L8). (if the date is invalid, the row will not be filtered). So when a user filters for a specific date they will always get a data item with a invalid value in the date

**Expected/desired behavior:**

* **What is the expected behavior?**
invalid dates are filtered out of the result set

* **What is the motivation / use case for changing the behavior?**
If there are a large number of `NULL` dates these will be included in the filter and the filter will seem broken to the user.

**Comment by ghiscoding** [comment]
I think that returning true will make it stay at same level while will make it move in the sort order

**Comment by jmzagorski** [comment]
I think the sorting acts weird too. Look at my screenshot in your example4. I added a null date for a bunch of records and the sort does not group the null dates together. The second screenshot is the filter not working too:

![image](https://user-images.githubusercontent.com/8404957/40378132-a5846810-5dc0-11e8-871b-efd2a41d2eb2.png)


![image](https://user-images.githubusercontent.com/8404957/40378173-c317f004-5dc0-11e8-8403-77a2b2d2d17d.png)

**Comment by ghiscoding** [comment]
I had some similar issues at the beginning in that same Example 4 with Description column, which is why I added some `null` in the dataset. I think the sort works correctly on string, maybe try to see if the Duration (number) is working when null are in the play. Also if the string is working correctly, then maybe there's some logic in that filter condition to make it work that the date doesn't have

**Comment by jmzagorski** [comment]
per the [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) it looks like the date sorters need to return -1 or 1 when the date values are null. 

The code changes below will need to be applied to all date sorters

**Soters**
```diff
- if (!moment(value1, FORMAT, true).isValid() || !moment(value2, FORMAT, true).isValid()) {
-    return 0;
-   }
+  let diff = 0;

+  if (!moment(value1, moment.ISO_8601).isValid()) {
+    diff = -1;
+  } else if (!moment(value2, moment.ISO_8601).isValid()) {
+    diff = 1;
+  } else {
+    const date1 = moment(value1);
+    const date2 = moment(value2);
+    diff = parseInt(date1.format('X'), 10) - parseInt(date2.format('X'), 10);
+  }
```

**Filters**
As for the date filters, if there is an invalid date then those need to return `false` and not `true`. 

I have these changes locally already and the sort and filters are working. There are no examples with dates for backend filters/sorters, but I would image it would function correctly too?

**Comment by ghiscoding** [comment]
Wow ok that got me confused for a few seconds, I didn't realized that we talked about 2 subjects in here (Filter and Sorter). 

I thought any Type would have to return `0` when invalid, but I guess I was wrong. If it works with that change then yes go ahead and please modify the Example 4 to include `null` dates so we can test it

For the Filters, I again thought it had to return `true` for representing no changes (or nothing found) but if it works better with `false` then go ahead and again have something to test it out in Example 4

**Comment by jmzagorski** [comment]
Originally this issue was just about Filters, but when you brought up sorters I decided to check that too. So it was a good thing we did talk about two different things so now it can be fixed 👍

**Comment by ghiscoding** [comment]
Yeah but from what I can see, we actually found 2 issues out of this subject lol 
I assume you will create PR(s) for the fixes.

Thanks

**Comment by jmzagorski** [comment]
Yes I will create two PRs for these
