### ISSUE TITLE
BUG - dispatchEvent should be cancelable 

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/aurelia-slickgrid#84]
**I'm submitting a bug report**

**Current behavior:**
All SlickGrid called through EventDispatch should be cancelable, and this requirement is necessary for some of the subscribed event. The event that I currently have problem with is `onBeforeEditCell` and as answered by the author of SlickGrid in this [SO](https://stackoverflow.com/a/4446926/1212166), the way to cancel an edit is to return `false` which doesn't do anything when currently used with EventDispatch

**Expected/desired behavior:**

* **What is the expected behavior?**
EventDispatch should be cancelable

* **What is the motivation / use case for changing the behavior?**
Have the same behavior as regular SlickGrid subscribed event.

**Comment by jmzagorski** [comment]
Yup good catch. I found this a while ago and I have a workaround in my app so it will be good to remove my workaround (sorry i should have submitted a PR when i found it). I use this feature to lock rows that have been "saved and committed" so users cannot further edit the row without explicitly unlocking it. Looking at your example here:

```typescript
  onBeforeEditCell(e, args) {
    return false; // this should cancel the edit
  }
```

and based on the docs for [dispatchEvent](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) the handling code should cancel the event by calling `e.preventDefault()` which will return false from `dispatchedEvent`.

**Comment by ghiscoding** [comment]
Yeah I encountered that problem yesterday and after searching a bit, then I found the DispatchEvent doc that event can be `cancelable` but aren't by default. However, there's something to note, SlickGrid is returning a modified version of an Event and if you try to run `e.preventDefault()` you will get an error that `preventDefault` is not a function (which I did and couldn't understand why it was throwing this error until I realized that SlickGrid modified the event). Anyhow, returning `true` (no stop) or `false` (cancel) will work.

I think that we should modify all the DispatchEvent, not just the ones with prefix (`asg`/`sg), unless you have objections for the other ones?

**Comment by jmzagorski** [comment]
in your example you can cancel the dispatched event with `preventDefault`, but you need to pass the underlying event to your method and not slickgrids

```diff
<aurelia-slickgrid 
   grid-id="grid1" 
   column-definitions.bind="columnDefinitions" 
   grid-options.bind="gridOptions" 
   dataset.bind="dataset"
-   sg-on-before-edit-cell.delegate="onBeforeEditCell($event.detail.eventData, $event.detail.args)">
+   sg-on-before-edit-cell.delegate="onBeforeEditCell($event)">
</aurelia-slickgrid>
```

If `preventDefault` is called, that will return false from `dispatchEvent`, which is what you want.  However, your method of `return false` works (and is cleaner) because of the great Aurelia Library. When you return false from a delegated event this is what aurelia does:

```javascript
    if (result !== true && this.preventDefault) {
      event.preventDefault();
    }
```

so there is no reason to call preventDefault in a view model, which is nice in my opinion.

Yes we should return the value from any dispatched event because of cancelled events.

**Comment by ghiscoding** [comment]
Oh that is interesting, thanks for that, I really didn't think about changing the arguments as I always do copy & paste lol.

What I like about Aurelia is that they follow the standard and Angular...not so much... and even `e.preventDefault()` doesn't prevent the editing.  I wouldn't be surprised that Angular doesn't handle returns of `dispatchEvent` return, this might be because in Aurelia we use `delegate` instead of `trigger` 

I might have to stick with the SlickGrid way until I find the solution (if there is) in Angular
```typescript
this.onBeforeEditSubscriber = this.angularGrid.slickGrid.onBeforeEditCell.subscribe((e, args) => {
    if (args.item && !this.isCellEditable(args.item, args.column)) {
      return false;
    }
});
```

**Comment by ghiscoding** [comment]
I actually found the problem with Angular, I forgot to return the `dispatchEvent` which is needed to return false

```diff
// ... this line
-    this.elm.dispatchEvent(new CustomEvent(eventName, eventInit));
+    return this.elm.dispatchEvent(new CustomEvent(eventName, eventInit));
```
That could help lol

I will push a commit to address this over the weekend, I will also do them as `cancelable` on all the `dispatchEvent`, not just the ones with prefix.
