### ISSUE TITLE
[Bug]: Demo page multiple select does not check selected items

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#95]
**I'm submitting a bug report**

* **Library Version:**
current

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Bundler used (WebPack/RequireJS/SystemJS**
WebPack

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
Demo page does not show the selected items in the multiple select editor under the prerequisites column. I am not sure if this is a prolem with the current version or the demo since I am not on the current version

**Expected/desired behavior:**

* **What is the expected behavior?**
multiple select editor has the selected items checked when select list is opened

* **What is the motivation / use case for changing the behavior?**
Demo page should behave as expected.

**Comment by ghiscoding** [comment]
You are right, I tested with choosing a new value but forgot to look at current value, sorry about that. This is most probably caused by my refactoring and merging of the previous 2 files into 1 file. I will take a look and fix it in the coming days. Thanks for reporting.
